---
config:
  look: classic
  theme: neutral
---

%%
%%  Copyright 2025, Contributors to the Grid Edge Interoperability & Security Alliance (GEISA) a Series of LF Projects, LLC  
%%  This file is licensed under the Community Specification License 1.0 available at:
%%  https://github.com/geisa/specification/blob/main/LICENSE.md or
%%  https://github.com/CommunitySpecification/Community_Specification/blob/main/1._Community_Specification_License-v1.md
%%
%%

sequenceDiagram
    participant C as LwM2M Client<br/>(GEISA Platform)
    participant S as LwM2M Server<br/>(GEISA EMS)
   
    S->>C: POST /2
    C->>S: 2.01 Created Location: /2/3
    S->>C: <br/>POST /2
    C->>S: 2.01 Created Location: /2/4
    S->>C: <br/>DELETE /2/3
    C->>S: 2.02 Deleted

