//-----------------------------------------------------------------------------
// Copyright 2025-2026, Contributors to the Grid Edge Interoperability &
// Security Alliance (GEISA), a Series of LF Projects, LLC
//
// Licensed under the Apache License, Version 2.0. See LICENSE.
//-----------------------------------------------------------------------------
//
// Example GEISA waveform subscribe + frame decoder
//
// This example demonstrates how an application can:
//   1) Serialize a GeisaWaveform_Req subscribe request (protobuf)
//   2) Parse a GeisaWaveform_Rsp subscribe response (protobuf) to obtain:
//        - waveform stream metadata (sample type, channel counts, rates)
//        - the per-application AF_UNIX SOCK_SEQPACKET socket path
//   3) Read and decode one geisa_waveform_frame from a unix socket or
//      fallback frame file path and print header fields, preview samples,
//      and min/max summary.
//
// Notes:
// - This example does not implement MQTT publish/subscribe. It emits and parses
//   protobuf payloads so you can wire them into your MQTT client of choice.
// - The waveform data-plane payload is a native binary frame (from unix
//   domain SOCK_SEQPACKET socket or fallback frame file path); it is not a
//   protobuf message.
//
// Build example:
//
//   make clean
//   make cpp
//   c++ -std=c++17 -O2 \
//     -I build/cpp \
//     $(pkg-config --cflags protobuf) \
//     examples/waveform_subscribe_and_read.cpp \
//     build/cpp/waveform.pb.cc \
//     build/cpp/geisa-status.pb.cc \
//     $(pkg-config --libs protobuf) \
//     -pthread \
//     -o /tmp/waveform_subscribe_and_read
//
// Usage:
//
//   # Writes a subscribe request protobuf payload:
//   /tmp/waveform_subscribe_and_read --write-req /tmp/waveform-req.bin
//
//   # Write a sample subscribe response protobuf payload:
//   /tmp/waveform_subscribe_and_read --write-rsp-sample /tmp/waveform-rsp.bin
//
//   # Parses a subscribe response protobuf payload and reads one waveform frame:
//   /tmp/waveform_subscribe_and_read --read-rsp /tmp/waveform-rsp.bin
//
//   # Runs a full demo (write sample response/frame, then read/decode):
//   /tmp/waveform_subscribe_and_read --demo
//
//------------------------------------------------------------------------------

#include <algorithm>
#include <cmath>
#include <cerrno>
#include <cstdlib>
#include <sysexits.h>
#include <cstdint>
#include <cstring>
#include <iomanip>
#include <iostream>
#include <limits>
#include <optional>
#include <sstream>
#include <string>
#include <vector>

#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/un.h>
#include <unistd.h>

#include "waveform.pb.h"      // generated by `make cpp`
#include "geisa-status.pb.h"  // generated by `make cpp` (included by
                              // waveform as well but explicit is fine)
#include "helpers/example_utils.h"

namespace {

/*
 * Matches the spec's geisa_waveform_frame header layout:
 *   int64 timestamp_ms
 *   uint32 sequence_num
 *   uint32 reserved
 * followed by samples payload
 *
 * Payload length is derived from recv() size.
 *
 * Sample interpretation depends on GeisaWaveform_SampleType and
 * total_channel_count.
 */
#pragma pack(push, 1)
struct GeisaWaveformFrameHeader {
  int64_t timestamp_ms;
  uint32_t sequence_num;
  uint32_t reserved;
};
#pragma pack(pop)

static_assert(sizeof(GeisaWaveformFrameHeader) == 16, "Unexpected header size");

int ConnectUnixSeqpacket(const std::string& path);
std::vector<uint8_t> RecvOneFrame(int fd);
void DecodeAndPrintFrame(const std::vector<uint8_t>& frame_bytes,
                         const GeisaWaveform_Rsp& rsp);

// File helpers used by demo/sample generation and by fallback decoding
// when `socket_path` is treated as a raw frame file path (for macOS - not
// needed for Linux)
std::string ReadAllFile(const std::string& path) {
  std::string bytes;
  if (!read_binary_file(path.c_str(), &bytes)) {
    throw std::runtime_error("Failed to open file: " + path);
  }
  return bytes;
}

void WriteAllFile(const std::string& path, const std::string& bytes) {
  if (!write_binary_file(path.c_str(), bytes)) {
    throw std::runtime_error("Failed to open file for write: " + path);
  }
}

int16_t ClampToInt16(long long v) {
  if (v < -32768) {
    return -32768;
  }
  if (v > 32767) {
    return 32767;
  }
  return static_cast<int16_t>(v);
}

std::string MakeSampleFrameBytes(const GeisaWaveform_Rsp& rsp) {
  // Build one frame for demo mode so parsing can be exercised without
  // a real platform waveform source..
  GeisaWaveformFrameHeader hdr{};
  hdr.timestamp_ms = 1735689600000LL;
  hdr.sequence_num = 1;
  hdr.reserved = 0;

  const uint32_t time_steps =
      (rsp.sample_rate_hz() * rsp.expected_frame_period_ms()) / 1000;
  const uint32_t channels = rsp.total_channel_count();
  constexpr double kPi = 3.14159265358979323846;
  const double w = 2.0 * kPi * static_cast<double>(rsp.nominal_frequency_hz());

  std::vector<int16_t> samples;
  samples.reserve(static_cast<size_t>(time_steps) * channels);

  for (uint32_t i = 0; i < time_steps; ++i) {
    const double t = static_cast<double>(i) /
                     static_cast<double>(rsp.sample_rate_hz());

    const double v_volts_peak = 339.4;
    const double v_volts = v_volts_peak * std::sin(w * t);
    const double i1_amps = 30.0 * std::sin(w * t - 0.05);
    const double i2_amps = 20.0 * std::sin(w * t + 0.07);

    const long long raw_v = std::llround(v_volts / rsp.voltage_scale());
    const long long raw_i1 = std::llround(i1_amps / rsp.current_scale());
    const long long raw_i2 = std::llround(i2_amps / rsp.current_scale());

    samples.push_back(ClampToInt16(raw_v));
    samples.push_back(ClampToInt16(raw_i1));
    samples.push_back(ClampToInt16(raw_i2));
  }

  std::string bytes(sizeof(hdr) + samples.size() * sizeof(int16_t), '\0');
  std::memcpy(bytes.data(), &hdr, sizeof(hdr));
  std::memcpy(bytes.data() + sizeof(hdr), samples.data(),
              samples.size() * sizeof(int16_t));
  return bytes;
}

bool IsRegularFile(const std::string& path) {
  struct stat st {};
  return ::stat(path.c_str(), &st) == 0 && S_ISREG(st.st_mode);
}

bool TryRecvOneFrameFromUnixSeqpacket(const std::string& path,
                                      std::vector<uint8_t>* frame,
                                      int* error_code,
                                      std::string* error_text) {

  // Preferred runtime path on Linux: one recv() returns one frame payload
  int fd = ::socket(AF_UNIX, SOCK_SEQPACKET, 0);
  if (fd < 0) {
    *error_code = errno;
    *error_text = "socket(AF_UNIX, SOCK_SEQPACKET) failed: " +
                  std::string(std::strerror(errno));
    return false;
  }

  sockaddr_un addr{};
  addr.sun_family = AF_UNIX;
  if (path.size() >= sizeof(addr.sun_path)) {
    *error_code = ENAMETOOLONG;
    *error_text = "Socket path too long: " + path;
    ::close(fd);
    return false;
  }
  std::strncpy(addr.sun_path, path.c_str(), sizeof(addr.sun_path) - 1);

  if (::connect(fd, reinterpret_cast<sockaddr*>(&addr), sizeof(addr)) != 0) {
    *error_code = errno;
    *error_text = "connect(" + path + ") failed: " +
                  std::string(std::strerror(errno));
    ::close(fd);
    return false;
  }

  std::vector<uint8_t> buf(1024 * 1024);  // 1 MiB
  ssize_t n = ::recv(fd, buf.data(), buf.size(), 0);
  if (n < 0) {
    *error_code = errno;
    *error_text = "recv failed: " + std::string(std::strerror(errno));
    ::close(fd);
    return false;
  }
  ::close(fd);

  buf.resize(static_cast<size_t>(n));
  *frame = std::move(buf);
  return true;
}

// Builds the sample response + single sample frame used by `--demo`
// and `--write-rsp-sample` modes.
//
// Frame is 200 ms at 7680 Hz with 1 voltage + 2 current int16 channels,
// approximating a US split-phase 2S meter and is written to `<rsp>.frame`.
void WriteRspSampleAndFrame(const std::string& rsp_path,
                            const char* program_name) {
  GeisaWaveform_Rsp rsp;
  rsp.mutable_status()->set_code(GEISA_STATUS_SUCCESS);
  rsp.mutable_status()->set_message("success");
  rsp.set_waveform_status(WAVEFORM_SUCCESS);
  rsp.set_stream_id("waveform-base");
  rsp.set_subscribed(true);
  rsp.set_socket_path(rsp_path + ".frame");
  rsp.set_sample_type(WAVEFORM_SAMPLE_TYPE_INT16);
  rsp.set_voltage_channel_count(1);
  rsp.set_current_channel_count(2);
  rsp.set_other_channel_count(0);
  rsp.set_total_channel_count(3);
  rsp.set_sample_rate_hz(7680);
  rsp.set_samples_per_cycle(128);
  rsp.set_nominal_frequency_hz(60);
  rsp.set_cycle_aligned(true);
  rsp.set_zero_crossing_aligned(true);
  rsp.set_voltage_scale(0.010359);
  rsp.set_current_scale(0.001220703125);
  rsp.set_expected_frame_period_ms(200);
  rsp.set_voltage_filter_lowpass(5000);
  rsp.set_current_filter_lowpass(5000);

  if (!serialize_protobuf_to_file(rsp_path.c_str(),
                                  rsp,
                                  "GeisaWaveform_Rsp")) {
    throw std::runtime_error("Failed to serialize GeisaWaveform_Rsp");
  }

  std::string frame_bytes = MakeSampleFrameBytes(rsp);
  WriteAllFile(rsp.socket_path(), frame_bytes);

  std::cout << "Wrote sample GeisaWaveform_Rsp (" << rsp.ByteSizeLong()
            << " bytes) to " << rsp_path << "\n";
  std::cout << "Wrote sample waveform frame (" << frame_bytes.size()
            << " bytes) to " << rsp.socket_path() << "\n";
  std::cout << program_name << " --read-rsp " << rsp_path << "\n";
}

void ReadRspAndProcessFrame(const std::string& path) {
  std::string bytes = ReadAllFile(path);

  // Control-plane response is protobuf; frame payload is a separate binary path
  GeisaWaveform_Rsp rsp;
  if (!rsp.ParseFromString(bytes)) {
    throw std::runtime_error("Failed to parse GeisaWaveform_Rsp from " + path);
  }

  std::cout << "Parsed GeisaWaveform_Rsp from " << path << "\n";
  std::cout << "status.code=" << GeisaStatusCode_Name(rsp.status().code())
            << " (" << static_cast<int>(rsp.status().code()) << ")"
            << " status.message=\"" << rsp.status().message() << "\"\n";
  std::cout << "waveform_status="
            << GeisaWaveform_Status_Name(rsp.waveform_status())
            << " (" << static_cast<int>(rsp.waveform_status()) << ")"
            << " stream_id=\"" << rsp.stream_id() << "\""
            << " subscribed=" << (rsp.subscribed() ? "true" : "false")
            << "\n";

  if (!rsp.subscribed()) {
    std::cout << "Not subscribed; nothing further to do.\n";
    return;
  }

  // Required metadata (for subscribed=true) is printed so operators can
  // verify channel layout and sample scaling assumptions before parsing
  std::cout << "socket_path=\"" << rsp.socket_path() << "\"\n";
  std::cout << "sample_type=" << rsp.sample_type()
            << " voltage_channel_count=" << rsp.voltage_channel_count()
            << " current_channel_count=" << rsp.current_channel_count()
            << " other_channel_count=" << rsp.other_channel_count()
            << " total_channel_count=" << rsp.total_channel_count()
            << " sample_rate_hz=" << rsp.sample_rate_hz()
            << " samples_per_cycle=" << rsp.samples_per_cycle()
            << " nominal_frequency_hz=" << rsp.nominal_frequency_hz()
            << " cycle_aligned=" << (rsp.cycle_aligned() ? "true" : "false")
            << " zero_crossing_aligned="
            << (rsp.zero_crossing_aligned() ? "true" : "false");
  if (rsp.voltage_filter_lowpass() != 0) {
    std::cout << " voltage_filter_lowpass=" << rsp.voltage_filter_lowpass();
  }
  if (rsp.current_filter_lowpass() != 0) {
    std::cout << " current_filter_lowpass=" << rsp.current_filter_lowpass();
  }
  std::cout << "\n";

  std::vector<uint8_t> frame;
  // Demo/dev fallback: if socket_path points to a regular file, read raw bytes
  // instead of using a unix socket data-plane.
  if (IsRegularFile(rsp.socket_path())) {
    std::string frame_file_bytes = ReadAllFile(rsp.socket_path());
    frame.assign(frame_file_bytes.begin(), frame_file_bytes.end());
    std::cout << "Read raw frame bytes from file \""
              << rsp.socket_path() << "\".\n";
  } else {
    int socket_error_code = 0;
    std::string socket_error_text;
    if (TryRecvOneFrameFromUnixSeqpacket(rsp.socket_path(), &frame,
                                         &socket_error_code,
                                         &socket_error_text)) {
      std::cout << "Connected to unix socket. Reading one frame...\n";
    } else {
      bool seqpacket_unsupported =
          socket_error_code == EPROTONOSUPPORT || socket_error_code == EINVAL;
#ifdef ENOTSUP
      seqpacket_unsupported =
          seqpacket_unsupported || socket_error_code == ENOTSUP;
#endif
#ifdef EOPNOTSUPP
      seqpacket_unsupported =
          seqpacket_unsupported || socket_error_code == EOPNOTSUPP;
#endif
      if (seqpacket_unsupported) {
        std::cout << "SOCK_SEQPACKET is not supported on this platform; "
                  << "falling back to raw frame file read.\n";
      } else {
        std::cout << "Socket read failed (" << socket_error_text
                  << "). Falling back to raw frame file read.\n";
      }
      if (!IsRegularFile(rsp.socket_path())) {
        throw std::runtime_error(socket_error_text);
      }
      std::string frame_file_bytes = ReadAllFile(rsp.socket_path());
      frame.assign(frame_file_bytes.begin(), frame_file_bytes.end());
      std::cout << "Read raw frame bytes from file \""
                << rsp.socket_path() << "\".\n";
    }
  }

  DecodeAndPrintFrame(frame, rsp);
}

size_t SampleSizeBytes(GeisaWaveform_SampleType t) {
  switch (t) {
    case WAVEFORM_SAMPLE_TYPE_INT16:
      return 2;
    case WAVEFORM_SAMPLE_TYPE_INT32:
      return 4;
    case WAVEFORM_SAMPLE_TYPE_FLOAT32:
      return 4;
    case WAVEFORM_SAMPLE_TYPE_FLOAT64:
      return 8;
    default:
      return 0;
  }
}

int ConnectUnixSeqpacket(const std::string& path) {
  int fd = ::socket(AF_UNIX, SOCK_SEQPACKET, 0);
  if (fd < 0) {
    throw std::runtime_error("socket(AF_UNIX, SOCK_SEQPACKET) failed: " +
                             std::string(std::strerror(errno)));
  }

  sockaddr_un addr{};
  addr.sun_family = AF_UNIX;
  if (path.size() >= sizeof(addr.sun_path)) {
    ::close(fd);
    throw std::runtime_error("Socket path too long: " + path);
  }
  std::strncpy(addr.sun_path, path.c_str(), sizeof(addr.sun_path) - 1);

  if (::connect(fd, reinterpret_cast<sockaddr*>(&addr), sizeof(addr)) != 0) {
    std::string err = std::strerror(errno);
    ::close(fd);
    throw std::runtime_error("connect(" + path + ") failed: " + err);
  }

  return fd;
}

// Reads exactly one frame message from a connected SOCK_SEQPACKET socket.
// SOCK_SEQPACKET preserves message boundaries, so one recv() corresponds
// to one geisa_waveform_frame payload.
std::vector<uint8_t> RecvOneFrame(int fd) {
  // Using a generous buffer for demo purposes.
  std::vector<uint8_t> buf(1024 * 1024);  // 1 MiB
  ssize_t n = ::recv(fd, buf.data(), buf.size(), 0);
  if (n < 0) {
    throw std::runtime_error("recv failed: " +
                             std::string(std::strerror(errno)));
  }
  buf.resize(static_cast<size_t>(n));
  return buf;
}

template <typename T>
void PrintRawPreviewByTimeStep(const uint8_t* payload,
                               size_t payload_len,
                               uint32_t total_channel_count,
                               size_t max_time_steps = 10) {
  if (total_channel_count == 0) {
    std::cout << "total_channel_count=0 (nothing to print)\n";
    return;
  }

  size_t sample_count = payload_len / sizeof(T);
  size_t time_steps = sample_count / total_channel_count;

  std::cout << "Preview first " << std::min(time_steps, max_time_steps)
            << " time steps (sample index). Channel order per step: [ch0";
  for (uint32_t ch = 1; ch < total_channel_count; ++ch) {
    std::cout << ", ch" << ch;
  }
  std::cout << "]\n";

  size_t steps_to_print = std::min(time_steps, max_time_steps);
  auto* samples = reinterpret_cast<const T*>(payload);

  for (size_t t = 0; t < steps_to_print; ++t) {
    std::cout << "t[" << t << "] raw:";
    for (uint32_t ch = 0; ch < total_channel_count; ++ch) {
      size_t idx = t * total_channel_count + ch;
      std::cout << " " << samples[idx];
    }
    std::cout << "\n";
  }
}

void PrintInt16RawAndScaledPreview(const uint8_t* payload,
                                   size_t payload_len,
                                   uint32_t total_channel_count,
                                   double voltage_scale,
                                   double current_scale,
                                   uint32_t sample_rate_hz,
                                   uint32_t expected_frame_period_ms,
                                   size_t max_time_steps = 10) {
  if (total_channel_count == 0) {
    std::cout << "total_channel_count=0 (nothing to print)\n";
    return;
  }

  size_t sample_count = payload_len / sizeof(int16_t);
  size_t time_steps = sample_count / total_channel_count;
  size_t steps_to_print = std::min(time_steps, max_time_steps);
  auto* samples = reinterpret_cast<const int16_t*>(payload);

  std::cout << "Interpretation:\n";
  std::cout << "  A time step is one sample instant.\n";
  std::cout << "  time_steps = sample_rate_hz * frame_period_ms / 1000.\n";
  std::cout
      << "  Typical US split-phase 2S service is 120/240V; demo ch0 "
      << "represents L1-L2 voltage (240 Vrms), ch1=Current leg A (I1), "
      << "ch2=Current leg B (I2).\n";
  std::cout << "  raw values are int16 samples from the frame payload.\n";
  std::cout
      << "  scaled values are engineering units from response scales "
      << "(voltage_scale/current_scale).\n";
  std::cout << "  scaled = raw * voltage_scale (V) or raw * "
               "current_scale (A).\n";
  std::cout << "  timestamp_ms is UTC epoch milliseconds; demo uses a fixed "
      << "example value.\n";
  std::cout << "  Frame period " << expected_frame_period_ms << " ms is about "
            << (static_cast<double>(expected_frame_period_ms) / 1000.0 * 60.0)
            << " cycles at 60 Hz.\n";
  std::cout
      << "  Use the min/max summary as a sanity check (demo expectation: "
      << "ch0 about +/-240 Vrms, i.e. roughly +/-339 V peak; currents "
      << "about +/-30A and +/-20A).\n";

  std::cout << "Preview first " << steps_to_print
            << " time steps (sample index). ";
  if (total_channel_count == 3) {
    std::cout << "Channel order per step: [ch0=V, ch1=I1, ch2=I2]\n";
    std::cout << "Preview columns: raw[V,I1,I2] (int16) | scaled[V,A,A] "
              << "(engineering units)\n";
  } else {
    std::cout << "Channel order per step: [ch0";
    for (uint32_t ch = 1; ch < total_channel_count; ++ch) {
      std::cout << ", ch" << ch;
    }
    std::cout << "]\n";
    std::cout << "Preview columns: raw[ch0..] | scaled[ch0..] "
              << "(ch0=V, ch1+=A)\n";
  }

  for (size_t t = 0; t < steps_to_print; ++t) {
    std::cout << "t[" << t << "] raw:";
    for (uint32_t ch = 0; ch < total_channel_count; ++ch) {
      size_t idx = t * total_channel_count + ch;
      std::cout << " " << samples[idx];
    }
    std::cout << " | scaled:";
    for (uint32_t ch = 0; ch < total_channel_count; ++ch) {
      size_t idx = t * total_channel_count + ch;
      const double scale = (ch == 0) ? voltage_scale : current_scale;
      const char* unit = (ch == 0) ? "V" : "A";
      std::ostringstream scaled_text;
      scaled_text << std::fixed << std::setprecision(3)
                  << (static_cast<double>(samples[idx]) * scale);
      std::cout << " " << scaled_text.str() << unit;
    }
    std::cout << "\n";
  }
}

template <typename T>
void PrintPerChannelRawMinMax(const uint8_t* payload,
                              size_t payload_len,
                              uint32_t total_channel_count) {
  if (total_channel_count == 0) {
    return;
  }
  size_t sample_count = payload_len / sizeof(T);
  size_t time_steps = sample_count / total_channel_count;
  auto* samples = reinterpret_cast<const T*>(payload);

  for (uint32_t ch = 0; ch < total_channel_count; ++ch) {
    T min_v = std::numeric_limits<T>::max();
    T max_v = std::numeric_limits<T>::lowest();
    for (size_t t = 0; t < time_steps; ++t) {
      const T v = samples[t * total_channel_count + ch];
      if (v < min_v) {
        min_v = v;
      }
      if (v > max_v) {
        max_v = v;
      }
    }
    std::cout << "ch" << ch << " raw_min=" << min_v
              << " raw_max=" << max_v << "\n";
  }
}

void PrintInt16ScaledMinMax(const uint8_t* payload,
                            size_t payload_len,
                            uint32_t total_channel_count,
                            double voltage_scale,
                            double current_scale) {
  if (total_channel_count == 0) {
    return;
  }
  size_t sample_count = payload_len / sizeof(int16_t);
  size_t time_steps = sample_count / total_channel_count;
  auto* samples = reinterpret_cast<const int16_t*>(payload);

  for (uint32_t ch = 0; ch < total_channel_count; ++ch) {
    int16_t min_raw = std::numeric_limits<int16_t>::max();
    int16_t max_raw = std::numeric_limits<int16_t>::lowest();
    for (size_t t = 0; t < time_steps; ++t) {
      const int16_t v = samples[t * total_channel_count + ch];
      if (v < min_raw) {
        min_raw = v;
      }
      if (v > max_raw) {
        max_raw = v;
      }
    }
    const double scale = (ch == 0) ? voltage_scale : current_scale;
    const char* unit = (ch == 0) ? "V" : "A";
    std::ostringstream min_text;
    min_text << std::fixed << std::setprecision(3)
             << (static_cast<double>(min_raw) * scale);
    std::ostringstream max_text;
    max_text << std::fixed << std::setprecision(3)
             << (static_cast<double>(max_raw) * scale);
    std::cout << "ch" << ch
              << " scaled_min=" << min_text.str() << unit
              << " scaled_max=" << max_text.str() << unit
              << "\n";
  }
}

// Decodes one geisa_waveform_frame (header + payload) and prints header fields,
// frame summary, interpretation legend, preview (first 10 time steps), and
// per-channel min/max.
//
// Payload detail: each time step stores channels in order from
// rsp.total_channel_count(); demo mapping is ch0=V, ch1=I1, ch2=I2.
void DecodeAndPrintFrame(const std::vector<uint8_t>& frame_bytes,
                         const GeisaWaveform_Rsp& rsp) {
  const GeisaWaveform_SampleType sample_type = rsp.sample_type();
  const uint32_t total_channel_count = rsp.total_channel_count();
  if (frame_bytes.size() < sizeof(GeisaWaveformFrameHeader)) {
    std::cout << "Frame too small: " << frame_bytes.size() << " bytes\n";
    return;
  }

  const auto* hdr =
      reinterpret_cast<const GeisaWaveformFrameHeader*>(frame_bytes.data());
  const uint8_t* payload =
      frame_bytes.data() + sizeof(GeisaWaveformFrameHeader);
  size_t payload_len = frame_bytes.size() - sizeof(GeisaWaveformFrameHeader);

  std::cout << "frame.timestamp_ms=" << hdr->timestamp_ms << "ms"
            << " sequence_num=" << hdr->sequence_num
            << " reserved=" << hdr->reserved
            << " payload_len=" << payload_len << "\n";

  size_t sz = SampleSizeBytes(sample_type);
  if (sz == 0) {
    std::cout << "Unknown/unsupported sample_type=" << sample_type << "\n";
    return;
  }
  if (payload_len % sz != 0) {
    std::cout << "Warning: payload_len not a multiple of sample size ("
              << sz << ")\n";
  }

  size_t sample_count = payload_len / sz;
  size_t time_steps =
      (total_channel_count == 0) ? 0 : (sample_count / total_channel_count);
  std::cout << "frame.summary: time_steps=" << time_steps
            << " sample_rate_hz=" << rsp.sample_rate_hz()
            << " expected_frame_period_ms=" << rsp.expected_frame_period_ms()
            << " channel_count=" << total_channel_count << "\n";

  switch (sample_type) {
    case WAVEFORM_SAMPLE_TYPE_INT16:
      PrintInt16RawAndScaledPreview(payload,
                                    payload_len,
                                    total_channel_count,
                                    rsp.voltage_scale(),
                                    rsp.current_scale(),
                                    rsp.sample_rate_hz(),
                                    rsp.expected_frame_period_ms(),
                                    10);
      PrintPerChannelRawMinMax<int16_t>(payload, payload_len,
                                        total_channel_count);
      PrintInt16ScaledMinMax(payload,
                             payload_len,
                             total_channel_count,
                             rsp.voltage_scale(),
                             rsp.current_scale());
      break;
    case WAVEFORM_SAMPLE_TYPE_INT32:
      PrintRawPreviewByTimeStep<int32_t>(payload, payload_len,
                                         total_channel_count, 10);
      PrintPerChannelRawMinMax<int32_t>(payload, payload_len,
                                        total_channel_count);
      break;
    case WAVEFORM_SAMPLE_TYPE_FLOAT32:
      PrintRawPreviewByTimeStep<float>(payload, payload_len,
                                       total_channel_count, 10);
      PrintPerChannelRawMinMax<float>(payload, payload_len,
                                       total_channel_count);
      break;
    case WAVEFORM_SAMPLE_TYPE_FLOAT64:
      PrintRawPreviewByTimeStep<double>(payload, payload_len,
                                        total_channel_count, 10);
      PrintPerChannelRawMinMax<double>(payload, payload_len,
                                       total_channel_count);
      break;
    default:
      std::cout << "Unsupported sample_type=" << sample_type << "\n";
      break;
  }
}
}

// Minimal demo CLI:
//
// 1) Generate a subscribe request protobuf (bytes) to a file:
//    ./waveform_subscribe_and_read --write-req /tmp/waveform_req.pb
//
// 2) Generate a sample waveform subscribe response protobuf (bytes) to a file:
//    ./waveform_subscribe_and_read --write-rsp-sample /tmp/waveform_rsp.pb
//
// 3) Parse a waveform subscribe response protobuf (bytes) from a file, then
//    connect to the socket-path inside it and read one frame:
//    ./waveform_subscribe_and_read --read-rsp /tmp/waveform_rsp.pb
//
// 4) Run the full local demo end-to-end:
//    ./waveform_subscribe_and_read --demo
//
// In practice/non-demo, your MQTT client would publish the req bytes to:
//   geisa/api/waveform/req/<userid>
// and subscribe for the rsp bytes from:
//   geisa/api/waveform/rsp/<userid>

int main(int argc, char** argv) {
  try {


    if (argc < 2) {
      return print_example_usage_and_return({
          "Usage:",
          std::string("  ") + argv[0] + " --write-req <path>",
          std::string("  ") + argv[0] + " --write-rsp-sample <path>",
          std::string("  ") + argv[0] + " --read-rsp <path>",
          std::string("  ") + argv[0] + " --demo"});
    }

    std::string mode = argv[1];

    GOOGLE_PROTOBUF_VERIFY_VERSION;

    if (mode == "--demo") {
      // End-to-end local flow: create control-plane sample + one frame payload,
      // then decode exactly as an integrator would..
      const std::string demo_rsp_path = "/tmp/waveform-rsp.bin";
      print_example_info_lines(
          {"Running waveform demo: write sample response + frame, then read/decode."});
      WriteRspSampleAndFrame(demo_rsp_path, argv[0]);
      ReadRspAndProcessFrame(demo_rsp_path);
      return EXIT_SUCCESS;
    }

    if (argc < 3) {
      return print_example_usage_and_return({
          std::string("Mode ") + mode + " requires <path>.",
          "Usage:",
          std::string("  ") + argv[0] + " --write-req <path>",
          std::string("  ") + argv[0] + " --write-rsp-sample <path>",
          std::string("  ") + argv[0] + " --read-rsp <path>",
          std::string("  ") + argv[0] + " --demo"});
    }

    std::string path = argv[2];

    if (mode == "--write-req") {
      // Request path demonstrates control-plane submission payload only.
      GeisaWaveform_Req req;
      req.set_stream_id("waveform-base");
      req.set_request_type(WAVEFORM_SUBSCRIBE);

      if (!serialize_protobuf_to_file(path.c_str(),
                                      req,
                                      "GeisaWaveform_Req")) {
        throw std::runtime_error("Failed to serialize GeisaWaveform_Req");
      }
      print_example_info_lines({
          std::string("Wrote GeisaWaveform_Req (")
              + std::to_string(req.ByteSizeLong()) + " bytes) to " + path,
          "Next steps:",
          std::string("  ") + argv[0] + " --demo",
          "Two-step alternative:",
          std::string("  ") + argv[0]
              + " --write-rsp-sample /tmp/waveform-rsp.bin",
          std::string("  ") + argv[0] + " --read-rsp /tmp/waveform-rsp.bin",
          "Integration notes (secondary):",
          std::string("  ") + path
              + " contains raw bytes of a serialized GeisaWaveform_Req protobuf payload.",
          "  1) Send those bytes to the platform using your existing GEISA transport.",
          "  2) Capture the platform's GeisaWaveform_Rsp raw bytes and save them to a file",
          "     (e.g. /tmp/waveform-rsp.bin).",
          "  (Common GEISA message topics for these payloads: geisa/api/waveform/req/<userid>,",
          "   geisa/api/waveform/rsp/<userid>.)"});
      return EXIT_SUCCESS;
    }

    if (mode == "--write-rsp-sample") {
      WriteRspSampleAndFrame(path, argv[0]);
      return EXIT_SUCCESS;
    }

    if (mode == "--read-rsp") {
      // Response path demonstrates control-plane parse + frame decode path.
      ReadRspAndProcessFrame(path);
      return EXIT_SUCCESS;
    }

    std::cerr << "Unknown mode: " << mode << "\n";
    return EX_USAGE;

  } catch (const std::exception& e) {
    std::cerr << "Error: " << e.what() << "\n";
    return EXIT_FAILURE;
  }
}
