..
  Copyright 2025-2026, Contributors to the Grid Edge Interoperability &
  Security Alliance (GEISA), a Series of LF Projects, LLC
  This file is licensed under the Community Specification License 1.0
  available at:
  https://github.com/geisa/specification/blob/main/LICENSE.md or
  https://github.com/CommunitySpecification/Community_Specification/blob/main/1._Community_Specification_License-v1.md

.. Actual master TOC, pulled in by index.rst and index-latex.rst 

GEISA Specification |release|
=================================

.. toctree::
   :maxdepth: 3
   :numbered:
   :includehidden:

   abstract
   contributors
   license

   introduction
   glossary
    
   design-principles
   operations
   system-architecture
   conformance
   hardware

   adm

   linux-environment
   virtual-environment

   api

   security

   revision-history

