..
  Copyright 2025-2026, Contributors to the Grid Edge Interoperability &
  Security Alliance (GEISA), a Series of LF Projects, LLC
  This file is licensed under the Community Specification License 1.0
  available at:
  https://github.com/geisa/specification/blob/main/LICENSE.md or
  https://github.com/CommunitySpecification/Community_Specification/blob/main/1._Community_Specification_License-v1.md

.. [CSNA20] `The Commercial National Security Algorithm Suite 2.0 and Quantum Computing FAQ
   <https://media.defense.gov/2022/Sep/07/2003071836/-1/-1/0/CSI_CNSA_2.0_FAQ_.PDF>`_

.. [FIPS186] `FIPS 186 Digital Signature Standard (DSS)
   <https://doi.org/10.6028/NIST.FIPS.186-5>`_

.. [FIPS204] `FIPS 204 Module-Lattice-Based Digital Signature Standard
   <https://doi.org/10.6028/NIST.FIPS.204>`_

.. [IEEE8021AR] `IEEE Standard for Local and metropolitan area networks–Secure Device Identity
   <https://1.ieee802.org/security/802-1ar/>`_

.. [LWM2M] `OMA Lightweight M2M
   <https://www.openmobilealliance.org/specifications/lwm2m>`_

.. [LWM2M-Core] `OMA SpecWorks Lightweight Machine to Machine Technical Specification Core 1.2
   <https://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.pdf>`_

.. [LWM2M-Transport] `OMA SpecWorks Lightweight Machine to Machine Technical Specification: Transport Bindings 1.2
   <https://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.pdf>`_

.. [NIST800-186] `NIST SP 800-186 Recommendations for Discrete Logarithm-based Cryptography: Elliptic Curve Domain Parameters
   <https://doi.org/10.6028/NIST.SP.800-186>`_

.. [RFC2119] `Key words for use in RFCs to Indicate Requirement Levels
   <https://datatracker.ietf.org/doc/html/rfc2119>`_

.. [RFC7252] `The Constrained Application Protocol (CoAP)
   <https://datatracker.ietf.org/doc/html/rfc7252>`_

.. [RFC9148] `EST-coaps: Enrollment over Secure Transport with the Secure Constrained Application Protocol
   <https://datatracker.ietf.org/doc/html/rfc9148>`_

.. [X509] `X.509 : Information technology - Open Systems Interconnection - The Directory: Public-key and attribute certificate frameworks
   <https://www.itu.int/rec/T-REC-X.509-201910-I/en>`_
